export const PRAYER_METHODS = [
  {id: '', label: "Choose a calculation method below", labelAr: "اختر طريقة الحساب أدناه"},
  { id: 1, label: "University of Islamic Sciences, Karachi", labelAr: "جامعة العلوم الإسلامية، كراتشي" },
  { id: 2, label: "Islamic Society of North America", labelAr: "الجمعية الإسلامية لأمريكا الشمالية" },
  { id: 3, label: "Muslim World League", labelAr: "رابطة العالم الإسلامي" },
  { id: 4, label: "Umm Al-Qura University, Makkah", labelAr: "جامعة أم القرى، مكة المكرمة" },
  { id: 5, label: "Egyptian General Authority of Survey", labelAr: "الهيئة المصرية العامة للمساحة" },
  { id: 7, label: "Institute of Geophysics, Tehran", labelAr: "معهد الجيوفيزياء، طهران" },
  { id: 8, label: "Gulf Region", labelAr: "منطقة الخليج" },
  { id: 9, label: "Kuwait", labelAr: "الكويت" },
  { id: 10, label: "Qatar", labelAr: "قطر" },
  { id: 11, label: "MUIS, Singapore", labelAr: "مجلس الشؤون الإسلامية، سنغافورة" },
  { id: 12, label: "UOIF, France", labelAr: "اتحاد المنظمات الإسلامية في فرنسا" },
  { id: 13, label: "Diyanet, Turkey", labelAr: "رئاسة الشؤون الدينية، تركيا" },
  { id: 14, label: "Russia", labelAr: "روسيا" },
  { id: 15, label: "Moonsighting Committee Worldwide", labelAr: "لجنة رؤية الهلال العالمية" },
  { id: 16, label: "Dubai (experimental)", labelAr: "دبي (تجريبي)" },
  { id: 17, label: "JAKIM, Malaysia", labelAr: "جاكيم، ماليزيا" },
  { id: 18, label: "Tunisia", labelAr: "تونس" },
  { id: 19, label: "Algeria", labelAr: "الجزائر" },
  { id: 20, label: "KEMENAG, Indonesia", labelAr: "وزارة الشؤون الدينية، إندونيسيا" },
  { id: 21, label: "Morocco", labelAr: "المغرب" },
  { id: 22, label: "Lisbon, Portugal", labelAr: "لشبونة، البرتغال" },
  { id: 23, label: "Jordan", labelAr: "الأردن" },
  { id: 0, label: "Jafari / Shia Ithna-Ashari", labelAr: "الجعفري / الشيعة الإثنا عشرية" }
];

export const ARABICTRANSLATION = {
  'Home': 'الرئيسية',
  'Asma Husna': 'أسماء الله الحسنى',
  'Prayer Times': 'مواقيت الصلاة',
  'Fasting Times': 'مواقيت الصيام',
  'Fajr': 'الفجر',
  'Sunrise': 'الشروق',
  'Dhuhr': 'الظهر',
  'Noon': 'الظهيرة',
  'Start': 'إبتداءا من',
  'End' : 'إلى',
  'Asr': 'العصر',
  'Maghrib': 'المغرب',
  'Isha': 'العشاء',
  'Sunset': 'الغروب',
  'Sahur': 'سحور',
  'Iftar': 'إفطار',
  'Duration': 'المدة',
  'White days': 'الأيام البيض',
  'And': 'و',
  'Calculation method': 'طريقة الحساب',
  'Prayer Times in': 'مواقيت الصلاة في',
  'Prohibited Times': 'الأوقات المنهي عنها',
  'From': 'من',
  'From Kaaba': 'من الكعبة',
  'Please wait': 'المرجو الإنتظار',
  'SIRAJ': 'سراج',
  'Light of': 'نور',
  'Guidance': 'الهداية',
  'Built for the Ummah as a free guide everyday': 'مصمم للأمة كدليل مجاني كل يوم'
}

