export const PRAYER_METHODS = [
  { id: 1, label: "University of Islamic Sciences, Karachi" },
  { id: 2, label: "Islamic Society of North America" },
  { id: 3, label: "Muslim World League" },
  { id: 4, label: "Umm Al-Qura University, Makkah" },
  { id: 5, label: "Egyptian General Authority of Survey" },
  { id: 7, label: "Institute of Geophysics, Tehran" },
  { id: 8, label: "Gulf Region" },
  { id: 9, label: "Kuwait" },
  { id: 10, label: "Qatar" },
  { id: 11, label: "MUIS, Singapore" },
  { id: 12, label: "UOIF, France" },
  { id: 13, label: "Diyanet, Turkey" },
  { id: 14, label: "Russia" },
  { id: 15, label: "Moonsighting Committee Worldwide" },
  { id: 16, label: "Dubai (experimental)" },
  { id: 17, label: "JAKIM, Malaysia" },
  { id: 18, label: "Tunisia" },
  { id: 19, label: "Algeria" },
  { id: 20, label: "KEMENAG, Indonesia" },
  { id: 21, label: "Morocco" },
  { id: 22, label: "Lisbon, Portugal" },
  { id: 23, label: "Jordan" },
  { id: 0, label: "Jafari / Shia Ithna-Ashari" }
];
